import Config

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :axon_dashboard, AxonDashboardWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}],
  check_origin: false,
  # REQ-AXO-901851 — hot-reload code/template activé pour la vélocité de dev.
  # ⚠️ dev ET live partagent MIX_ENV=dev (mix phx.server) → ceci s'applique
  # AUSSI au live tant que la séparation MIX_ENV (live→prod) n'est pas faite.
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "9goHzbAlJOE1YJBZsH2rZP6dZ8xHFxQWHyt9zRQusARsCENnMsEm0ZIlO6ZK8W7A",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:axon_dashboard, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:axon_dashboard, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Auto browser refresh (live_reload) requiert le dep phoenix_live_reload
# (only: :dev), absent de mix.exs — REQ-AXO-901851 follow-up. code_reloader
# ci-dessus suffit pour que les édits réapparaissent au reload manuel.
# config :axon_dashboard, AxonDashboardWeb.Endpoint,
#   live_reload: [ ... ]  # voir historique git ; réactiver après ajout du dep

# Enable dev routes for dashboard and mailbox
config :axon_dashboard, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
